In [1]:
%matplotlib inline

In [2]:
import numpy as np
import matplotlib.pyplot as plt

## Live demos

In [27]:
def f(num):
    return num**2

In [10]:
a = 2

In [8]:
delta =np.array(np.power(10.0, np.arange(0, -11, -1)))

In [9]:
print(delta)

[1.e+00 1.e-01 1.e-02 1.e-03 1.e-04 1.e-05 1.e-06 1.e-07 1.e-08 1.e-09
 1.e-10]


In [11]:
a - delta

array([1.        , 1.9       , 1.99      , 1.999     , 1.9999    ,
       1.99999   , 1.999999  , 1.9999999 , 1.99999999, 2.        ,
       2.        ])

In [13]:
(a + delta)[::-1]

array([2.        , 2.        , 2.00000001, 2.0000001 , 2.000001  ,
       2.00001   , 2.0001    , 2.001     , 2.01      , 2.1       ,
       3.        ])

In [20]:
x = np.append(a-delta, (a + delta)[::-1])
print(x)

[1.         1.9        1.99       1.999      1.9999     1.99999
 1.999999   1.9999999  1.99999999 2.         2.         2.
 2.         2.00000001 2.0000001  2.000001   2.00001    2.0001
 2.001      2.01       2.1        3.        ]


In [25]:
x

array([1.        , 1.9       , 1.99      , 1.999     , 1.9999    ,
       1.99999   , 1.999999  , 1.9999999 , 1.99999999, 2.        ,
       2.        , 2.        , 2.        , 2.00000001, 2.0000001 ,
       2.000001  , 2.00001   , 2.0001    , 2.001     , 2.01      ,
       2.1       , 3.        ])

In [28]:
y = f(x)

In [29]:
list(zip(x,y))

[(1.0, 1.0),
 (1.9, 3.61),
 (1.99, 3.9601),
 (1.999, 3.9960010000000006),
 (1.9999, 3.99960001),
 (1.99999, 3.9999600000999997),
 (1.999999, 3.9999960000010004),
 (1.9999999, 3.99999960000001),
 (1.99999999, 3.9999999600000002),
 (1.999999999, 3.9999999959999997),
 (1.9999999999, 3.9999999996),
 (2.0000000001, 4.0000000004),
 (2.000000001, 4.000000004),
 (2.00000001, 4.00000004),
 (2.0000001, 4.000000400000009),
 (2.000001, 4.000004000001001),
 (2.00001, 4.0000400001),
 (2.0001, 4.000400010000001),
 (2.001, 4.004001),
 (2.01, 4.040099999999999),
 (2.1, 4.41),
 (3.0, 9.0)]

In [30]:
def get_limit(f, a):
    epsilon = np.array([10 **p for p in np.arange(0, -11, -1, dtype = float)])
    x = np.append(a -epsilon, (a + epsilon)[::-1])
    y = f(x)
    return y
print(get_limit(lambda x: x**2,3))
print(get_limit(lambda x: x**2 + 3*x ,2))
print(get_limit(lambda x: np.sin(x),0))

[ 4.          8.41        8.9401      8.994001    8.99940001  8.99994
  8.999994    8.9999994   8.99999994  8.99999999  9.          9.
  9.00000001  9.00000006  9.0000006   9.000006    9.00006     9.00060001
  9.006001    9.0601      9.61       16.        ]
[ 4.          9.31        9.9301      9.993001    9.99930001  9.99993
  9.999993    9.9999993   9.99999993  9.99999999 10.         10.
 10.00000001 10.00000007 10.0000007  10.000007   10.00007    10.00070001
 10.007001   10.0701     10.71       18.        ]
[-8.41470985e-01 -9.98334166e-02 -9.99983333e-03 -9.99999833e-04
 -9.99999998e-05 -1.00000000e-05 -1.00000000e-06 -1.00000000e-07
 -1.00000000e-08 -1.00000000e-09 -1.00000000e-10  1.00000000e-10
  1.00000000e-09  1.00000000e-08  1.00000000e-07  1.00000000e-06
  1.00000000e-05  9.99999998e-05  9.99999833e-04  9.99983333e-03
  9.98334166e-02  8.41470985e-01]


In [31]:
def calculate_derivative(f, a, h = 1e-7):
    return (f(a + h) - f(a))/h

In [37]:
def quad_polinomila(x):
    return 3 * x**2 + 5*x - 8

In [40]:
print(calculate_derivative(quad_polinomila, 3, 1e-7))

23.00000026878024


In [41]:
print(calculate_derivative(lambda x: x**4 - x**3 -3, 3, 1e-7))

81.0000044282333
